// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubhmnwvfzxxnsjgnyere.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViaG1ud3Zmenh4bnNqZ255ZXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MjgxMzEsImV4cCI6MjA2OTEwNDEzMX0.S66QvY33vk1S1Z1JNqDTe75lxD8Jwf_BMujH-vofgSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});